# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='idUsuario',
        ),
    ]
