# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181008_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='posterino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posterino+', to='posts.Post'),
        ),
    ]
